#!/usr/bin/env python3
"""Turn full-resolution masters into the web derivatives the AReA page loads progressively.

For every master image (PNG/JPEG/WebP/TIFF) in SRC this writes the page's display files to static/img/<id>/:

    w800  w1600  w2400  w3200 .avif       display sizes, picked by the browser (srcset/sizes)
    w800  w1600  w2400  w3200 .webp       fallback for browsers without AVIF
    w1600.jpg                             last-resort fallback

and, for masters larger than the biggest display size, the full-resolution file, apart from the page's files, to
full/<id>.jpg (progressive JPEG); smaller masters zoom into their largest display file instead. The page never loads
it on open: it is fetched only when a viewer zooms in or uses the magnifier, and each figure links to it.

and records the image in static/data/images.js (size, available widths, the HQ file, and a ~600 byte blurred
placeholder that is shown before anything is downloaded). Widths larger than the master are skipped. The masters
themselves never go into the repo: keep them outside it (or under area/masters/, which is git-ignored).

    python3 area/tools/build_images.py SRC            # build everything that is new or changed
    python3 area/tools/build_images.py SRC --force    # rebuild everything
    python3 area/tools/build_images.py SRC --only teaser fig5_bottle_area
    python3 area/tools/build_images.py SRC --only teaser --lens teaser=0.849,0.227

--lens ID=X,Y also cuts static/img/<id>/lens.jpg, a small full-resolution crop around X,Y (fractions of the image):
a magnifier parked there shows it sharp before the full-resolution file is fetched.

The id is the master's file name without its extension (lowercase, use - or _ only).
Needs ImageMagick (convert/identify) and ffmpeg with libaom-av1 (for AVIF; skipped with a warning if missing).
"""
import argparse
import base64
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
AREA = os.path.dirname(HERE)
OUT = os.path.join(AREA, 'static', 'img')
FULL = os.path.join(AREA, 'full')  # full-resolution files: in the repo, outside the page's static files
MANIFEST = os.path.join(AREA, 'static', 'data', 'images.js')

WIDTHS = [800, 1600, 2400, 3200]
JPEG_FALLBACK = 1600
HQ_MAX = 16384  # longest side of the zoom file; larger masters are scaled down to this
Q = {'avif_crf': 20, 'webp': 90, 'jpg': 90, 'hq': 90}
EXTS = ('.png', '.jpg', '.jpeg', '.webp', '.tif', '.tiff')


def run(cmd):
    r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if r.returncode:
        sys.exit(f'failed: {" ".join(cmd)}\n{r.stderr.strip()}')
    return r.stdout


def size_of(path):
    w, h = run(['identify', '-format', '%w %h', path + '[0]']).split()
    return int(w), int(h)


def resize(src, dst, width, quality, extra=()):
    run(['convert', src + '[0]', '-colorspace', 'sRGB', '-alpha', 'remove', '-alpha', 'off', '-filter', 'Lanczos',
         '-resize', f'{width}x', '-strip', *extra, '-quality', str(quality), dst])


def avif(src_png, dst):
    if not shutil.which('ffmpeg'):
        return False
    r = subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', src_png, '-vf', 'pad=ceil(iw/2)*2:ceil(ih/2)*2',
                        '-c:v', 'libaom-av1', '-still-picture', '1', '-crf', str(Q['avif_crf']), '-cpu-used', '6',
                        '-pix_fmt', 'yuv420p', dst], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    return r.returncode == 0 and os.path.getsize(dst) > 0


def lqip(src):
    with tempfile.TemporaryDirectory() as t:
        p = os.path.join(t, 'l.jpg')
        run(['convert', src + '[0]', '-colorspace', 'sRGB', '-alpha', 'remove', '-alpha', 'off', '-resize', '32x',
             '-strip', '-blur', '0x0.6', '-quality', '45', p])
        with open(p, 'rb') as f:
            return 'data:image/jpeg;base64,' + base64.b64encode(f.read()).decode()


def load_manifest():
    if not os.path.exists(MANIFEST):
        return {}
    txt = open(MANIFEST).read()
    m = re.search(r'=\s*(\{.*\})\s*;?\s*$', txt, re.S)
    return json.loads(m.group(1)) if m else {}


def save_manifest(data):
    os.makedirs(os.path.dirname(MANIFEST), exist_ok=True)
    body = json.dumps(dict(sorted(data.items())), indent=1)
    with open(MANIFEST, 'w') as f:
        f.write('// Generated by area/tools/build_images.py; do not edit by hand.\n')
        f.write('window.AREA_IMAGES = ' + body + ';\n')


LENS_SIDE = 0.09  # the parked-lens crop: this fraction of the image's width, square (a 4x lens shows ~6.5%)


def lens_crop(path, iid, w, h, x, y):
    side = round(LENS_SIDE * w)
    x0 = min(max(0, round(x * w - side / 2)), w - side)
    y0 = min(max(0, round(y * h - side / 2)), h - side)
    run(['convert', path + '[0]', '-colorspace', 'sRGB', '-alpha', 'remove', '-alpha', 'off', '-crop', f'{side}x{side}+{x0}+{y0}',
         '+repage', '-strip', '-interlace', 'Plane', '-quality', '86', os.path.join(OUT, iid, 'lens.jpg')])
    return {'src': f'static/img/{iid}/lens.jpg', 'x0': x0 / w, 'y0': y0 / h, 'x1': (x0 + side) / w, 'y1': (y0 + side) / h}


def build(path, force):
    iid = os.path.splitext(os.path.basename(path))[0]
    if not re.fullmatch(r'[a-z0-9][a-z0-9_-]*', iid):
        sys.exit(f'{os.path.basename(path)}: use lowercase letters, digits, - and _ in master file names')
    out = os.path.join(OUT, iid)
    stamp = os.path.join(out, '.source')
    sig = f'{os.path.getsize(path)}:{int(os.path.getmtime(path))}'
    if not force and os.path.exists(stamp) and open(stamp).read() == sig:
        return iid, None
    shutil.rmtree(out, ignore_errors=True)
    os.makedirs(out)
    w, h = size_of(path)
    widths = sorted({x for x in WIDTHS if x < w} | {min(w, WIDTHS[-1])})
    formats = ['webp', 'jpg']
    has_avif = True
    with tempfile.TemporaryDirectory() as t:
        for x in widths:
            png = os.path.join(t, f'{x}.png')
            resize(path, png, x, 100)
            if has_avif and not avif(png, os.path.join(out, f'w{x}.avif')):
                has_avif = False
                print('  ! AVIF encoding unavailable; serving WebP/JPEG only', file=sys.stderr)
            resize(png, os.path.join(out, f'w{x}.webp'), x, Q['webp'], ['-define', 'webp:method=6'])
        fb = min(widths, key=lambda x: abs(x - JPEG_FALLBACK))
        resize(path, os.path.join(out, f'w{fb}.jpg'), fb, Q['jpg'], ['-interlace', 'Plane', '-sampling-factor', '4:2:0'])
    if has_avif:
        formats.insert(0, 'avif')
    for f in os.listdir(out):  # an AVIF set is all-or-nothing
        if f.endswith('.avif') and not has_avif:
            os.remove(os.path.join(out, f))
    hw = min(w, HQ_MAX) if w >= h else round(w * min(h, HQ_MAX) / h)
    hq_w, hq_h = hw, round(h * hw / w)
    old_full = os.path.join(FULL, f'{iid}.jpg')
    if os.path.exists(old_full):
        os.remove(old_full)
    if w <= WIDTHS[-1]:
        # the largest display file already holds every pixel: zoom uses it, no separate full-resolution copy
        top = widths[-1]
        hq = {'src': f'static/img/{iid}/w{top}.webp', 'w': top, 'h': round(h * top / w),
              'bytes': os.path.getsize(os.path.join(out, f'w{top}.webp'))}
    else:
        os.makedirs(FULL, exist_ok=True)
        full = os.path.join(FULL, f'{iid}.jpg')
        resize(path, full, hq_w, Q['hq'], ['-interlace', 'Plane', '-sampling-factor', '4:2:0'])
        if os.path.getsize(full) > 95e6:
            print(f'  ! {iid}: full-resolution file is {os.path.getsize(full) / 1e6:.0f} MB; GitHub refuses files over 100 MB',
                  file=sys.stderr)
        hq = {'src': f'full/{iid}.jpg', 'w': hq_w, 'h': hq_h, 'bytes': os.path.getsize(full)}
    entry = {
        'w': w, 'h': h, 'widths': widths, 'formats': formats, 'fallback': fb,
        'hq': hq,
        'lqip': lqip(path),
    }
    with open(stamp, 'w') as f:
        f.write(sig)
    return iid, entry


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('src', help='folder with the full-resolution masters (or a single file)')
    ap.add_argument('--force', action='store_true', help='rebuild even if the master is unchanged')
    ap.add_argument('--only', nargs='*', help='ids to build (default: all)')
    ap.add_argument('--prune', action='store_true', help='drop manifest entries whose master is gone from SRC')
    ap.add_argument('--lens', action='append', default=[], metavar='ID=X,Y',
                    help='cut a full-resolution crop for a magnifier parked at X,Y (fractions)')
    a = ap.parse_args()
    files = [a.src] if os.path.isfile(a.src) else sorted(
        os.path.join(a.src, f) for f in os.listdir(a.src) if f.lower().endswith(EXTS))
    if a.only:
        files = [f for f in files if os.path.splitext(os.path.basename(f))[0] in a.only]
    data = load_manifest()
    for f in files:
        iid, entry = build(f, a.force)
        if entry is None:
            if iid in data:
                print(f'  = {iid} (unchanged)')
                continue
            iid, entry = build(f, True)
        data[iid] = entry
        for spec in a.lens:
            lid, xy = spec.split('=')
            if lid == iid:
                x, y = (float(v) for v in xy.split(','))
                entry['lens'] = lens_crop(f, iid, entry['w'], entry['h'], x, y)
        kb = sum(os.path.getsize(os.path.join(OUT, iid, x)) for x in os.listdir(os.path.join(OUT, iid))) / 1e3
        print(f'  + {iid}: {entry["w"]}x{entry["h"]} -> {entry["widths"]} {"/".join(entry["formats"])}, '
              f'hq {entry["hq"]["w"]}x{entry["hq"]["h"]} ({entry["hq"]["bytes"] / 1e6:.1f} MB), {kb / 1e3:.1f} MB total')
    if a.prune and os.path.isdir(a.src):
        keep = {os.path.splitext(os.path.basename(f))[0] for f in files}
        for iid in [k for k in data if k not in keep]:
            data.pop(iid)
            shutil.rmtree(os.path.join(OUT, iid), ignore_errors=True)
            if os.path.exists(os.path.join(FULL, f'{iid}.jpg')):
                os.remove(os.path.join(FULL, f'{iid}.jpg'))
            print(f'  - {iid}')
    save_manifest(data)


if __name__ == '__main__':
    main()
